filter:
    excluded_paths:
        - 'Tests/*'
        - 'Documentation/*'
    paths:
        - 'Classes/*'
        - 'Configuration/*'

checks:
    php:
        remove_extra_empty_lines: true
        uppercase_constants: true
        properties_in_camelcaps: true
        phpunit_assertions: true
        parameters_in_camelcaps: true
        parameter_doc_comments: true
        encourage_single_quotes: true

tools:
    external_code_coverage:
        timeout: 700
        runs: 1

    php_cpd:
        enabled: true

    php_code_sniffer:
        enabled: true
        config:
            standard: "PSR2"

    php_cs_fixer:
        enabled: true

    php_hhvm:
        enabled: true
        config:
            use_undeclared_constant:  false

    php_mess_detector:
        enabled: true
        config:
            controversial_rules:
                superglobals: false

    php_pdepend:
        enabled: true

    php_analyzer:
        enabled: true

    sensiolabs_security_checker: true