language: php
sudo: false

cache:
  directories:
    - $HOME/.composer/cache

notifications:
  email:
    recipients:
      - tomasnorre@gmail.com
    on_success: never
    on_failure: never


addons:
  apt:
    packages:
      - parallel

before_install:
  - composer self-update
  - composer --version

before_script:
  # Installs TYPO3
  - composer require typo3/cms-core=$TYPO3_VERSION
  # Restore composer.json
  - git checkout composer.json
  - export "TYPO3_PATH_WEB"=$PWD/.Build/Web;
  # Locating UnitTests.xml
  - export "UNIT_XML"=`find . -name 'UnitTests.xml' -type f`
  # Location FunctionalTests.xml
  - export "FUNCTIONAL_XML"=`find . -name 'FunctionalTests.xml' -type f`
  - ln -nfs .Build/vendor/typo3/cms/typo3 typo3
script:
  - >
    echo;
    echo "Running php lint";
    find . -name \*.php ! -path "./.Build/*" ! -path "./scripts/*" ! -path "./typo3_src/*" | parallel --gnu php -d display_errors=stderr -l {} > /dev/null \;
  - >
    if [[ "$COVERAGE" == "0" ]]; then
      echo;
      echo "Running unit tests";
      .Build/bin/phpunit --colors -c $UNIT_XML Tests/Unit/
    fi
  - >
    if [[ "$COVERAGE" == "1" ]]; then
      echo;
      echo "Running unit tests";
      .Build/bin/phpunit --coverage-clover=unittest-coverage.clover --colors -c $UNIT_XML Tests/Unit/
    fi
  - >
    if [[ "$FUNCTIONAL" == "1" ]]; then
      echo;
      echo "Running functional tests";
      export typo3DatabaseName="typo3";
      export typo3DatabaseHost="localhost";
      export typo3DatabaseUsername="root";
      export typo3DatabasePassword="";
      find 'Tests/Functional' -wholename '*Test.php' | parallel --gnu 'echo; echo "Running functional test suite {}"; .Build/bin/phpunit --coverage-clover={}functionaltest-coverage.clover --colors  -c $FUNCTIONAL_XML {}'
    fi
  - >
    if [[ "$COVERAGE" == "1" ]]; then
      echo;
      echo "Uploading code coverage results";
      wget https://scrutinizer-ci.com/ocular.phar
      php ocular.phar code-coverage:upload --format=php-clover unittest-coverage.clover
      find 'Tests/Functional' -wholename '*Test.php' -exec php ocular.phar code-coverage:upload --format=php-clover {}functionaltest-coverage.clover \;
    fi

jobs:
  allow_failure:
    - env: TYPO3_VERSION=dev-master COVERAGE=0 FUNCTIONAL=1
    - env: TYPO3_VERSION=dev-master COVERAGE=0 FUNCTIONAL=0
  include:
    - stage: test
      php: 7.2
      env: TYPO3_VERSION=^9.5 COVERAGE=0 FUNCTIONAL=0
    - stage: test
      php: 7.2
      env: TYPO3_VERSION=^9.5 COVERAGE=0 FUNCTIONAL=1
    - stage: test
      php: 7.3
      env: TYPO3_VERSION=dev-master COVERAGE=0 FUNCTIONAL=0
    - stage: test
      php: 7.3
      env: TYPO3_VERSION=dev-master COVERAGE=0 FUNCTIONAL=1

    - stage: ship to ter
      if: tag IS present
      php: 7.0
      install: skip
      before_script: skip
      script:
        - |
          if [ -n "$TYPO3_ORG_USERNAME" ] && [ -n "$TYPO3_ORG_PASSWORD" ]; then
            echo -e "Preparing upload of release ${TRAVIS_TAG} to TER\n";
            # Install ter client
            composer global require helhum/ter-client
            # Build extension files
            ####composer extension-release
            # Upload
            TAG_MESSAGE=`git tag -n10 -l $TRAVIS_TAG | sed 's/^[0-9.]*[ ]*//g'`
            echo "Uploading release ${TRAVIS_TAG} to TER"
            ###$HOME/.composer/vendor/bin/ter-client upload typo3_console . -u "$TYPO3_ORG_USERNAME" -p "$TYPO3_ORG_PASSWORD" -m "$TAG_MESSAGE"
          fi;