<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "golf_courses"
 *
 * Auto generated by Extension Builder 2016-08-04
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
	'title' => 'Golf Courses',
	'description' => 'Displayed which golf courses played',
	'category' => 'plugin',
	'author' => 'Tomas Norre Mikkelsen',
	'author_email' => 'tomasnorre@gmail.com',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '1',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '',
	'constraints' => [
		'depends' => [
			'typo3' => '7.6.0-8.9.99',
			'static_info_tables' => '',
		],
		'conflicts' => [
		],
		'suggests' => [
		],
	],
];